//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// 
// This source code was auto-generated by wsdl, Version=4.0.30319.33440.
// 
namespace PaladinPharmacyCOMv1.Example.Client.WebService
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Collections.Generic;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "PharmacyCOMSoap", Namespace = "http://services.paladinpos.com/PaladinPharmacyCOMv1")]
    public partial class PharmacyCOM : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback GetRxItemOperationCompleted;

        private System.Threading.SendOrPostCallback SaveRxInvoiceOperationCompleted;

        private System.Threading.SendOrPostCallback GetAvailableCreditOperationCompleted;

        private System.Threading.SendOrPostCallback SaveInvoiceOperationCompleted;

        /// <remarks/>
        public PharmacyCOM()
        {
            this.Url = "";
        }

        /// <remarks/>
        public event GetRxItemCompletedEventHandler GetRxItemCompleted;

        /// <remarks/>
        public event SaveRxInvoiceCompletedEventHandler SaveRxInvoiceCompleted;

        /// <remarks/>
        public event GetAvailableCreditCompletedEventHandler GetAvailableCreditCompleted;

        /// <remarks/>
        public event SaveInvoiceCompletedEventHandler SaveInvoiceCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.paladinpos.com/PaladinPharmacyCOMv1/GetRxItem", RequestNamespace = "http://services.paladinpos.com/PaladinPharmacyCOMv1", ResponseNamespace = "http://services.paladinpos.com/PaladinPharmacyCOMv1", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RxItem GetRxItem(string rxNumber)
        {
            object[] results = this.Invoke("GetRxItem", new object[] {
                        rxNumber});
            return ((RxItem)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetRxItem(string rxNumber, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetRxItem", new object[] {
                        rxNumber}, callback, asyncState);
        }

        /// <remarks/>
        public RxItem EndGetRxItem(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((RxItem)(results[0]));
        }

        /// <remarks/>
        public void GetRxItemAsync(string rxNumber)
        {
            this.GetRxItemAsync(rxNumber, null);
        }

        /// <remarks/>
        public void GetRxItemAsync(string rxNumber, object userState)
        {
            if ((this.GetRxItemOperationCompleted == null))
            {
                this.GetRxItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRxItemOperationCompleted);
            }
            this.InvokeAsync("GetRxItem", new object[] {
                        rxNumber}, this.GetRxItemOperationCompleted, userState);
        }

        private void OnGetRxItemOperationCompleted(object arg)
        {
            if ((this.GetRxItemCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRxItemCompleted(this, new GetRxItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.paladinpos.com/PaladinPharmacyCOMv1/SaveRxInvoice", RequestNamespace = "http://services.paladinpos.com/PaladinPharmacyCOMv1", ResponseNamespace = "http://services.paladinpos.com/PaladinPharmacyCOMv1", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SaveRxInvoice(RxInvoice rxInvoice)
        {
            object[] results = this.Invoke("SaveRxInvoice", new object[] {
                        rxInvoice});
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginSaveRxInvoice(RxInvoice rxInvoice, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("SaveRxInvoice", new object[] {
                        rxInvoice}, callback, asyncState);
        }

        /// <remarks/>
        public bool EndSaveRxInvoice(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public void SaveRxInvoiceAsync(RxInvoice rxInvoice)
        {
            this.SaveRxInvoiceAsync(rxInvoice, null);
        }

        /// <remarks/>
        public void SaveRxInvoiceAsync(RxInvoice rxInvoice, object userState)
        {
            if ((this.SaveRxInvoiceOperationCompleted == null))
            {
                this.SaveRxInvoiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveRxInvoiceOperationCompleted);
            }
            this.InvokeAsync("SaveRxInvoice", new object[] {
                        rxInvoice}, this.SaveRxInvoiceOperationCompleted, userState);
        }

        private void OnSaveRxInvoiceOperationCompleted(object arg)
        {
            if ((this.SaveRxInvoiceCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveRxInvoiceCompleted(this, new SaveRxInvoiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.paladinpos.com/PaladinPharmacyCOMv1/GetAvailableCredit", RequestNamespace = "http://services.paladinpos.com/PaladinPharmacyCOMv1", ResponseNamespace = "http://services.paladinpos.com/PaladinPharmacyCOMv1", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AvailableCreditResponse GetAvailableCredit(string customerId)
        {
            object[] results = this.Invoke("GetAvailableCredit", new object[] {
                        customerId});
            return ((AvailableCreditResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginGetAvailableCredit(string customerId, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("GetAvailableCredit", new object[] {
                        customerId}, callback, asyncState);
        }

        /// <remarks/>
        public AvailableCreditResponse EndGetAvailableCredit(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((AvailableCreditResponse)(results[0]));
        }

        /// <remarks/>
        public void GetAvailableCreditAsync(string customerId)
        {
            this.GetAvailableCreditAsync(customerId, null);
        }

        /// <remarks/>
        public void GetAvailableCreditAsync(string customerId, object userState)
        {
            if ((this.GetAvailableCreditOperationCompleted == null))
            {
                this.GetAvailableCreditOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAvailableCreditOperationCompleted);
            }
            this.InvokeAsync("GetAvailableCredit", new object[] {
                        customerId}, this.GetAvailableCreditOperationCompleted, userState);
        }

        private void OnGetAvailableCreditOperationCompleted(object arg)
        {
            if ((this.GetAvailableCreditCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAvailableCreditCompleted(this, new GetAvailableCreditCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://services.paladinpos.com/PaladinPharmacyCOMv1/SaveInvoice", RequestNamespace = "http://services.paladinpos.com/PaladinPharmacyCOMv1", ResponseNamespace = "http://services.paladinpos.com/PaladinPharmacyCOMv1", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SaveInvoice(Invoice invoice)
        {
            object[] results = this.Invoke("SaveInvoice", new object[] {
                        invoice});
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginSaveInvoice(Invoice invoice, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("SaveInvoice", new object[] {
                        invoice}, callback, asyncState);
        }

        /// <remarks/>
        public bool EndSaveInvoice(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public void SaveInvoiceAsync(Invoice invoice)
        {
            this.SaveInvoiceAsync(invoice, null);
        }

        /// <remarks/>
        public void SaveInvoiceAsync(Invoice invoice, object userState)
        {
            if ((this.SaveInvoiceOperationCompleted == null))
            {
                this.SaveInvoiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveInvoiceOperationCompleted);
            }
            this.InvokeAsync("SaveInvoice", new object[] {
                        invoice}, this.SaveInvoiceOperationCompleted, userState);
        }

        private void OnSaveInvoiceOperationCompleted(object arg)
        {
            if ((this.SaveInvoiceCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveInvoiceCompleted(this, new SaveInvoiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://services.paladinpos.com/PaladinPharmacyCOMv1")]
    public partial class RxItem
    {

        private string rxNumberField;

        private bool rxValidField;

        private string rxCustomerNameField;

        private string rxCustomerFNameField;

        private string rxCustomerMNameField;

        private string rxCustomerLNameField;

        private string rxPatientIDField;

        private string rxCustomerPhone1Field;

        private string rxCustomerRegAddress1Field;

        private string rxCustomerRegAddress2Field;

        private string rxCustomerRegCityField;

        private string rxCustomerRegStateField;

        private string rxCustomerRegZIPField;

        private decimal rxAmountDueField;

        private bool rxTaxableField;

        private List<RxMessage> rxMessagesField;

        private List<RxItemFlag> rxItemFlagsField;

        /// <remarks/>
        public string RxNumber
        {
            get
            {
                return this.rxNumberField;
            }
            set
            {
                this.rxNumberField = value;
            }
        }

        /// <remarks/>
        public bool RxValid
        {
            get
            {
                return this.rxValidField;
            }
            set
            {
                this.rxValidField = value;
            }
        }

        /// <remarks/>
        public string RxCustomerName
        {
            get
            {
                return this.rxCustomerNameField;
            }
            set
            {
                this.rxCustomerNameField = value;
            }
        }

        /// <remarks/>
        public string RxCustomerFName
        {
            get
            {
                return this.rxCustomerFNameField;
            }
            set
            {
                this.rxCustomerFNameField = value;
            }
        }

        /// <remarks/>
        public string RxCustomerMName
        {
            get
            {
                return this.rxCustomerMNameField;
            }
            set
            {
                this.rxCustomerMNameField = value;
            }
        }

        /// <remarks/>
        public string RxCustomerLName
        {
            get
            {
                return this.rxCustomerLNameField;
            }
            set
            {
                this.rxCustomerLNameField = value;
            }
        }

        /// <remarks/>
        public string RxPatientID
        {
            get
            {
                return this.rxPatientIDField;
            }
            set
            {
                this.rxPatientIDField = value;
            }
        }

        /// <remarks/>
        public string RxCustomerPhone1
        {
            get
            {
                return this.rxCustomerPhone1Field;
            }
            set
            {
                this.rxCustomerPhone1Field = value;
            }
        }

        /// <remarks/>
        public string RxCustomerRegAddress1
        {
            get
            {
                return this.rxCustomerRegAddress1Field;
            }
            set
            {
                this.rxCustomerRegAddress1Field = value;
            }
        }

        /// <remarks/>
        public string RxCustomerRegAddress2
        {
            get
            {
                return this.rxCustomerRegAddress2Field;
            }
            set
            {
                this.rxCustomerRegAddress2Field = value;
            }
        }

        /// <remarks/>
        public string RxCustomerRegCity
        {
            get
            {
                return this.rxCustomerRegCityField;
            }
            set
            {
                this.rxCustomerRegCityField = value;
            }
        }

        /// <remarks/>
        public string RxCustomerRegState
        {
            get
            {
                return this.rxCustomerRegStateField;
            }
            set
            {
                this.rxCustomerRegStateField = value;
            }
        }

        /// <remarks/>
        public string RxCustomerRegZIP
        {
            get
            {
                return this.rxCustomerRegZIPField;
            }
            set
            {
                this.rxCustomerRegZIPField = value;
            }
        }

        /// <remarks/>
        public decimal RxAmountDue
        {
            get
            {
                return this.rxAmountDueField;
            }
            set
            {
                this.rxAmountDueField = value;
            }
        }

        /// <remarks/>
        public bool RxTaxable
        {
            get
            {
                return this.rxTaxableField;
            }
            set
            {
                this.rxTaxableField = value;
            }
        }

        /// <remarks/>
        public List<RxMessage> RxMessages
        {
            get
            {
                return this.rxMessagesField;
            }
            set
            {
                this.rxMessagesField = value;
            }
        }

        /// <remarks/>
        public List<RxItemFlag> RxItemFlags
        {
            get
            {
                return this.rxItemFlagsField;
            }
            set
            {
                this.rxItemFlagsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://services.paladinpos.com/PaladinPharmacyCOMv1")]
    public partial class RxMessage
    {

        private string messageField;

        private bool printField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Print
        {
            get
            {
                return this.printField;
            }
            set
            {
                this.printField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://services.paladinpos.com/PaladinPharmacyCOMv1")]
    public partial class InvoiceRxItemFlag
    {

        private string customerIdField;

        private string customerNameField;

        private System.Nullable<int> typeField;

        private System.Nullable<bool> acceptedField;

        private byte[] signatureField;

        /// <remarks/>
        public string CustomerId
        {
            get
            {
                return this.customerIdField;
            }
            set
            {
                this.customerIdField = value;
            }
        }

        /// <remarks/>
        public string CustomerName
        {
            get
            {
                return this.customerNameField;
            }
            set
            {
                this.customerNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<bool> Accepted
        {
            get
            {
                return this.acceptedField;
            }
            set
            {
                this.acceptedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
        public byte[] Signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://services.paladinpos.com/PaladinPharmacyCOMv1")]
    public partial class InvoiceTax
    {

        private int idField;

        private int invoiceIdField;

        private string nameField;

        private System.Nullable<int> typeField;

        private System.Nullable<decimal> rateField;

        private System.Nullable<decimal> amountField;

        private System.Nullable<int> categoriesField;

        private string expansionField;

        /// <remarks/>
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public int InvoiceId
        {
            get
            {
                return this.invoiceIdField;
            }
            set
            {
                this.invoiceIdField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> Rate
        {
            get
            {
                return this.rateField;
            }
            set
            {
                this.rateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> Categories
        {
            get
            {
                return this.categoriesField;
            }
            set
            {
                this.categoriesField = value;
            }
        }

        /// <remarks/>
        public string Expansion
        {
            get
            {
                return this.expansionField;
            }
            set
            {
                this.expansionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://services.paladinpos.com/PaladinPharmacyCOMv1")]
    public partial class InvoicePayment
    {

        private int invoiceIdField;

        private int lineNumberField;

        private System.Nullable<System.DateTime> dateField;

        private System.Nullable<int> typeField;

        private System.Nullable<decimal> amountField;

        private string dataField;

        private System.Nullable<int> saleIdField;

        private System.Nullable<int> categoriesField;

        private string expansionField;

        /// <remarks/>
        public int InvoiceId
        {
            get
            {
                return this.invoiceIdField;
            }
            set
            {
                this.invoiceIdField = value;
            }
        }

        /// <remarks/>
        public int LineNumber
        {
            get
            {
                return this.lineNumberField;
            }
            set
            {
                this.lineNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        /// <remarks/>
        public string Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> SaleId
        {
            get
            {
                return this.saleIdField;
            }
            set
            {
                this.saleIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> Categories
        {
            get
            {
                return this.categoriesField;
            }
            set
            {
                this.categoriesField = value;
            }
        }

        /// <remarks/>
        public string Expansion
        {
            get
            {
                return this.expansionField;
            }
            set
            {
                this.expansionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://services.paladinpos.com/PaladinPharmacyCOMv1")]
    public partial class InvoiceText
    {

        private int invoiceIdField;

        private int lineNumberField;

        private string valueField;

        private System.Nullable<int> categoriesField;

        private string expansionField;

        /// <remarks/>
        public int InvoiceId
        {
            get
            {
                return this.invoiceIdField;
            }
            set
            {
                this.invoiceIdField = value;
            }
        }

        /// <remarks/>
        public int LineNumber
        {
            get
            {
                return this.lineNumberField;
            }
            set
            {
                this.lineNumberField = value;
            }
        }

        /// <remarks/>
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> Categories
        {
            get
            {
                return this.categoriesField;
            }
            set
            {
                this.categoriesField = value;
            }
        }

        /// <remarks/>
        public string Expansion
        {
            get
            {
                return this.expansionField;
            }
            set
            {
                this.expansionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://services.paladinpos.com/PaladinPharmacyCOMv1")]
    public partial class InvoiceItem
    {

        private int invoiceIdField;

        private int lineNumberField;

        private System.Nullable<int> inventoryIdField;

        private System.Nullable<System.DateTime> dateField;

        private string partNumberField;

        private string descriptionField;

        private string primaryNumberField;

        private System.Nullable<int> departmentIdField;

        private System.Nullable<decimal> quantitySoldField;

        private System.Nullable<decimal> reorderQuantityField;

        private System.Nullable<decimal> retailPriceField;

        private System.Nullable<decimal> sellPriceField;

        private System.Nullable<decimal> soldPriceField;

        private System.Nullable<int> sellThresholdField;

        private System.Nullable<bool> taxableField;

        private System.Nullable<bool> netField;

        private System.Nullable<bool> defectiveField;

        private System.Nullable<decimal> lineExtField;

        private System.Nullable<decimal> promptPaymentDiscountField;

        private System.Nullable<decimal> profitField;

        private System.Nullable<decimal> costPerUnitField;

        private System.Nullable<decimal> costLineExtField;

        private System.Nullable<int> priceTypeField;

        private System.Nullable<int> pricingPlanIdField;

        private System.Nullable<int> saleIdField;

        private System.Nullable<int> supplierId1Field;

        private System.Nullable<int> supplierId2Field;

        private System.Nullable<int> classId1Field;

        private System.Nullable<int> subclassId1Field;

        private System.Nullable<int> classId2Field;

        private System.Nullable<int> subclassId2Field;

        private System.Nullable<int> classId3Field;

        private System.Nullable<int> subclassId3Field;

        private string expansionField;

        private System.Nullable<bool> flexItemField;

        private System.Nullable<int> storeIdField;

        private System.Nullable<int> categoriesField;

        private System.Nullable<bool> rxItemField;

        /// <remarks/>
        public int InvoiceId
        {
            get
            {
                return this.invoiceIdField;
            }
            set
            {
                this.invoiceIdField = value;
            }
        }

        /// <remarks/>
        public int LineNumber
        {
            get
            {
                return this.lineNumberField;
            }
            set
            {
                this.lineNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> InventoryId
        {
            get
            {
                return this.inventoryIdField;
            }
            set
            {
                this.inventoryIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }

        /// <remarks/>
        public string PartNumber
        {
            get
            {
                return this.partNumberField;
            }
            set
            {
                this.partNumberField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string PrimaryNumber
        {
            get
            {
                return this.primaryNumberField;
            }
            set
            {
                this.primaryNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> DepartmentId
        {
            get
            {
                return this.departmentIdField;
            }
            set
            {
                this.departmentIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> QuantitySold
        {
            get
            {
                return this.quantitySoldField;
            }
            set
            {
                this.quantitySoldField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> ReorderQuantity
        {
            get
            {
                return this.reorderQuantityField;
            }
            set
            {
                this.reorderQuantityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> RetailPrice
        {
            get
            {
                return this.retailPriceField;
            }
            set
            {
                this.retailPriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> SellPrice
        {
            get
            {
                return this.sellPriceField;
            }
            set
            {
                this.sellPriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> SoldPrice
        {
            get
            {
                return this.soldPriceField;
            }
            set
            {
                this.soldPriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> SellThreshold
        {
            get
            {
                return this.sellThresholdField;
            }
            set
            {
                this.sellThresholdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<bool> Taxable
        {
            get
            {
                return this.taxableField;
            }
            set
            {
                this.taxableField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<bool> Net
        {
            get
            {
                return this.netField;
            }
            set
            {
                this.netField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<bool> Defective
        {
            get
            {
                return this.defectiveField;
            }
            set
            {
                this.defectiveField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> LineExt
        {
            get
            {
                return this.lineExtField;
            }
            set
            {
                this.lineExtField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> PromptPaymentDiscount
        {
            get
            {
                return this.promptPaymentDiscountField;
            }
            set
            {
                this.promptPaymentDiscountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> Profit
        {
            get
            {
                return this.profitField;
            }
            set
            {
                this.profitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> CostPerUnit
        {
            get
            {
                return this.costPerUnitField;
            }
            set
            {
                this.costPerUnitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> CostLineExt
        {
            get
            {
                return this.costLineExtField;
            }
            set
            {
                this.costLineExtField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> PriceType
        {
            get
            {
                return this.priceTypeField;
            }
            set
            {
                this.priceTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> PricingPlanId
        {
            get
            {
                return this.pricingPlanIdField;
            }
            set
            {
                this.pricingPlanIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> SaleId
        {
            get
            {
                return this.saleIdField;
            }
            set
            {
                this.saleIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> SupplierId1
        {
            get
            {
                return this.supplierId1Field;
            }
            set
            {
                this.supplierId1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> SupplierId2
        {
            get
            {
                return this.supplierId2Field;
            }
            set
            {
                this.supplierId2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> ClassId1
        {
            get
            {
                return this.classId1Field;
            }
            set
            {
                this.classId1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> SubclassId1
        {
            get
            {
                return this.subclassId1Field;
            }
            set
            {
                this.subclassId1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> ClassId2
        {
            get
            {
                return this.classId2Field;
            }
            set
            {
                this.classId2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> SubclassId2
        {
            get
            {
                return this.subclassId2Field;
            }
            set
            {
                this.subclassId2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> ClassId3
        {
            get
            {
                return this.classId3Field;
            }
            set
            {
                this.classId3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> SubclassId3
        {
            get
            {
                return this.subclassId3Field;
            }
            set
            {
                this.subclassId3Field = value;
            }
        }

        /// <remarks/>
        public string Expansion
        {
            get
            {
                return this.expansionField;
            }
            set
            {
                this.expansionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<bool> FlexItem
        {
            get
            {
                return this.flexItemField;
            }
            set
            {
                this.flexItemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> StoreId
        {
            get
            {
                return this.storeIdField;
            }
            set
            {
                this.storeIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> Categories
        {
            get
            {
                return this.categoriesField;
            }
            set
            {
                this.categoriesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<bool> RxItem
        {
            get
            {
                return this.rxItemField;
            }
            set
            {
                this.rxItemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://services.paladinpos.com/PaladinPharmacyCOMv1")]
    public partial class Invoice
    {

        private int idField;

        private System.Nullable<bool> deletedField;

        private System.Nullable<int> numberField;

        private System.Nullable<System.DateTime> dateField;

        private System.Nullable<int> accountNumberField;

        private string accountNameField;

        private string pharmacyAccountNumberField;

        private System.Nullable<int> accountTrackerField;

        private System.Nullable<int> terminalNumberField;

        private System.Nullable<int> employeeNumberField;

        private string purchaseOrderNumberField;

        private System.Nullable<decimal> totalField;

        private System.Nullable<decimal> profitField;

        private System.Nullable<decimal> promptPaymentDiscountField;

        private System.Nullable<bool> globalTaxField;

        private System.Nullable<bool> globalNetField;

        private System.Nullable<bool> globalDefectiveField;

        private System.Nullable<bool> defaultTaxOverrideField;

        private System.Nullable<int> invoiceTypeField;

        private byte[] signatureField;

        private string expansionField;

        private System.Nullable<decimal> flexTotalField;

        private System.Nullable<int> storeIdField;

        private string customerRewardNumberField;

        private System.Nullable<int> categoriesField;

        private List<InvoiceItem> invoiceItemsField;

        private List<InvoiceText> invoiceTextField;

        private List<InvoicePayment> invoicePaymentsField;

        private List<InvoiceTax> invoiceTaxesField;

        private List<InvoiceRxItemFlag> invoiceRxItemFlagsField;

        /// <remarks/>
        public int Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<bool> Deleted
        {
            get
            {
                return this.deletedField;
            }
            set
            {
                this.deletedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<System.DateTime> Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> AccountNumber
        {
            get
            {
                return this.accountNumberField;
            }
            set
            {
                this.accountNumberField = value;
            }
        }

        /// <remarks/>
        public string AccountName
        {
            get
            {
                return this.accountNameField;
            }
            set
            {
                this.accountNameField = value;
            }
        }

        /// <remarks/>
        public string PharmacyAccountNumber
        {
            get
            {
                return this.pharmacyAccountNumberField;
            }
            set
            {
                this.pharmacyAccountNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> AccountTracker
        {
            get
            {
                return this.accountTrackerField;
            }
            set
            {
                this.accountTrackerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> TerminalNumber
        {
            get
            {
                return this.terminalNumberField;
            }
            set
            {
                this.terminalNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> EmployeeNumber
        {
            get
            {
                return this.employeeNumberField;
            }
            set
            {
                this.employeeNumberField = value;
            }
        }

        /// <remarks/>
        public string PurchaseOrderNumber
        {
            get
            {
                return this.purchaseOrderNumberField;
            }
            set
            {
                this.purchaseOrderNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> Total
        {
            get
            {
                return this.totalField;
            }
            set
            {
                this.totalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> Profit
        {
            get
            {
                return this.profitField;
            }
            set
            {
                this.profitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> PromptPaymentDiscount
        {
            get
            {
                return this.promptPaymentDiscountField;
            }
            set
            {
                this.promptPaymentDiscountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<bool> GlobalTax
        {
            get
            {
                return this.globalTaxField;
            }
            set
            {
                this.globalTaxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<bool> GlobalNet
        {
            get
            {
                return this.globalNetField;
            }
            set
            {
                this.globalNetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<bool> GlobalDefective
        {
            get
            {
                return this.globalDefectiveField;
            }
            set
            {
                this.globalDefectiveField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<bool> DefaultTaxOverride
        {
            get
            {
                return this.defaultTaxOverrideField;
            }
            set
            {
                this.defaultTaxOverrideField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> InvoiceType
        {
            get
            {
                return this.invoiceTypeField;
            }
            set
            {
                this.invoiceTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
        public byte[] Signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }

        /// <remarks/>
        public string Expansion
        {
            get
            {
                return this.expansionField;
            }
            set
            {
                this.expansionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> FlexTotal
        {
            get
            {
                return this.flexTotalField;
            }
            set
            {
                this.flexTotalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> StoreId
        {
            get
            {
                return this.storeIdField;
            }
            set
            {
                this.storeIdField = value;
            }
        }

        /// <remarks/>
        public string CustomerRewardNumber
        {
            get
            {
                return this.customerRewardNumberField;
            }
            set
            {
                this.customerRewardNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> Categories
        {
            get
            {
                return this.categoriesField;
            }
            set
            {
                this.categoriesField = value;
            }
        }

        /// <remarks/>
        public List<InvoiceItem> InvoiceItems
        {
            get
            {
                return this.invoiceItemsField;
            }
            set
            {
                this.invoiceItemsField = value;
            }
        }

        /// <remarks/>
        public List<InvoiceText> InvoiceText
        {
            get
            {
                return this.invoiceTextField;
            }
            set
            {
                this.invoiceTextField = value;
            }
        }

        /// <remarks/>
        public List<InvoicePayment> InvoicePayments
        {
            get
            {
                return this.invoicePaymentsField;
            }
            set
            {
                this.invoicePaymentsField = value;
            }
        }

        /// <remarks/>
        public List<InvoiceTax> InvoiceTaxes
        {
            get
            {
                return this.invoiceTaxesField;
            }
            set
            {
                this.invoiceTaxesField = value;
            }
        }

        /// <remarks/>
        public List<InvoiceRxItemFlag> InvoiceRxItemFlags
        {
            get
            {
                return this.invoiceRxItemFlagsField;
            }
            set
            {
                this.invoiceRxItemFlagsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://services.paladinpos.com/PaladinPharmacyCOMv1")]
    public partial class AvailableCreditResponse
    {

        private string customerIdField;

        private bool isValidField;

        private string messageField;

        private decimal availableCreditField;

        private decimal accountBalanceField;

        /// <remarks/>
        public string CustomerId
        {
            get
            {
                return this.customerIdField;
            }
            set
            {
                this.customerIdField = value;
            }
        }

        /// <remarks/>
        public bool IsValid
        {
            get
            {
                return this.isValidField;
            }
            set
            {
                this.isValidField = value;
            }
        }

        /// <remarks/>
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        public decimal AvailableCredit
        {
            get
            {
                return this.availableCreditField;
            }
            set
            {
                this.availableCreditField = value;
            }
        }

        /// <remarks/>
        public decimal AccountBalance
        {
            get
            {
                return this.accountBalanceField;
            }
            set
            {
                this.accountBalanceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://services.paladinpos.com/PaladinPharmacyCOMv1")]
    public partial class RxItemFlagResult
    {

        private byte[] signatureField;

        private string customerNameField;

        private int typeField;

        private bool acceptedField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
        public byte[] Signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CustomerName
        {
            get
            {
                return this.customerNameField;
            }
            set
            {
                this.customerNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Accepted
        {
            get
            {
                return this.acceptedField;
            }
            set
            {
                this.acceptedField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://services.paladinpos.com/PaladinPharmacyCOMv1")]
    public partial class RxPayment
    {

        private int typeField;

        private decimal amountField;

        private string messageField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://services.paladinpos.com/PaladinPharmacyCOMv1")]
    public partial class RxInvoice
    {

        private int rxInvoiceNumberField;

        private System.DateTime rxInvoiceDateField;

        private decimal rxSubTotalField;

        private decimal rxTaxTotalField;

        private decimal rxTotalField;

        private List<RxItem> rxItemsField;

        private List<RxPayment> rxPaymentsField;

        private List<RxItemFlagResult> rxItemFlagResultsField;

        /// <remarks/>
        public int RxInvoiceNumber
        {
            get
            {
                return this.rxInvoiceNumberField;
            }
            set
            {
                this.rxInvoiceNumberField = value;
            }
        }

        /// <remarks/>
        public System.DateTime RxInvoiceDate
        {
            get
            {
                return this.rxInvoiceDateField;
            }
            set
            {
                this.rxInvoiceDateField = value;
            }
        }

        /// <remarks/>
        public decimal RxSubTotal
        {
            get
            {
                return this.rxSubTotalField;
            }
            set
            {
                this.rxSubTotalField = value;
            }
        }

        /// <remarks/>
        public decimal RxTaxTotal
        {
            get
            {
                return this.rxTaxTotalField;
            }
            set
            {
                this.rxTaxTotalField = value;
            }
        }

        /// <remarks/>
        public decimal RxTotal
        {
            get
            {
                return this.rxTotalField;
            }
            set
            {
                this.rxTotalField = value;
            }
        }

        /// <remarks/>
        public List<RxItem> RxItems
        {
            get
            {
                return this.rxItemsField;
            }
            set
            {
                this.rxItemsField = value;
            }
        }

        /// <remarks/>
        public List<RxPayment> RxPayments
        {
            get
            {
                return this.rxPaymentsField;
            }
            set
            {
                this.rxPaymentsField = value;
            }
        }

        /// <remarks/>
        public List<RxItemFlagResult> RxItemFlagResults
        {
            get
            {
                return this.rxItemFlagResultsField;
            }
            set
            {
                this.rxItemFlagResultsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://services.paladinpos.com/PaladinPharmacyCOMv1")]
    public partial class RxItemFlag
    {

        private int typeField;

        private string messageField;

        private bool requiredField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Required
        {
            get
            {
                return this.requiredField;
            }
            set
            {
                this.requiredField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void GetRxItemCompletedEventHandler(object sender, GetRxItemCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRxItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetRxItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public RxItem Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((RxItem)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void SaveRxInvoiceCompletedEventHandler(object sender, SaveRxInvoiceCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveRxInvoiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal SaveRxInvoiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public bool Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void GetAvailableCreditCompletedEventHandler(object sender, GetAvailableCreditCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAvailableCreditCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetAvailableCreditCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public AvailableCreditResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((AvailableCreditResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void SaveInvoiceCompletedEventHandler(object sender, SaveInvoiceCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveInvoiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal SaveInvoiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public bool Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}
